name: HardcoreFactions
version: 1.0-SNAPSHOT
main: com.altoya.hardcorefactions.Main
api-version: 1.13

commands:
  f:
    description: Factions general command
    usage: /f <Required> <Subcommand Dependant>